### ISSUE TITLE
SSL problem

### ISSUE THREAD

**Issue by blade2005** [rbauction/sfdclib#1]
```
>>> import sfdclib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cdavis/.local/lib/python3.5/site-packages/sfdclib/__init__.py", line 7, in <module>
    from sfdclib.session import (
  File "/home/cdavis/.local/lib/python3.5/site-packages/sfdclib/session.py", line 3, in <module>
    from requests import Session
  File "/home/cdavis/.local/lib/python3.5/site-packages/requests/__init__.py", line 78, in <module>
    from urllib3.contrib import pyopenssl
  File "/home/cdavis/.local/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/home/cdavis/.local/lib/python3.5/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/home/cdavis/.local/lib/python3.5/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/home/cdavis/.local/lib/python3.5/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/home/cdavis/.local/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 156, in <module>
    Binding.init_static_locks()
  File "/home/cdavis/.local/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/home/cdavis/.local/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "/home/cdavis/.local/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 84, in build_conditional_library
    if not getattr(lib, condition):
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_SCRYPT'
```

I've also seen this same problem relating to Cryptography_HAS_EVP_PKEY_DHX and Cryptography_HAS_MEM_FUNCTIONS.

cryptography (1.9)
cffi (1.8.3)
sfdclib (0.2.15)
pyOpenSSL (17.0.0)

**Comment by ashevtsov-rba** [comment]
I noticed you are using Python 3.5. We only tested the library with v3.3 and v3.4. Can you downgrade Python to 3.3 or 3.4 and try again?

**Comment by blade2005** [comment]
Well it turns out I broke something with my ssl. Once I downgraded my ssl in my user and started using default sitewide ssl sfdclib started working.
